import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import { COLORS, RADIUS, SHADOW, SPACING } from "../../constants/theme";
import type { Property } from "../../types/property";

export default function PropertyCard({ property, onPress }: { property: Property; onPress: () => void }) {
  const specs = [property.areaValue > 0 ? `${property.areaValue} ${property.areaUnit}` : "", property.bedrooms > 0 ? `${property.bedrooms} Bed` : "", property.bathrooms > 0 ? `${property.bathrooms} Bath` : "", property.parking].filter(Boolean);
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}>
    {property.coverImageUrl ? <Image source={{ uri: property.coverImageUrl }} style={styles.image} resizeMode="cover" /> : <View style={[styles.image, styles.placeholder]}><Text style={styles.placeholderText}>JMK ASSETS</Text></View>}
    <View style={styles.badges}><Text style={styles.type}>{property.type}</Text>{property.featured && <Text style={styles.featured}>Featured</Text>}</View>
    <View style={styles.body}><View style={styles.row}><Text style={styles.price}>{property.price}</Text><Text style={[styles.status, property.status === "Sold" && styles.sold]}>{property.status}</Text></View><Text style={styles.title} numberOfLines={2}>{property.title}</Text><Text style={styles.location} numberOfLines={2}>⌖ {property.location}</Text>{specs.length > 0 && <Text style={styles.specs} numberOfLines={2}>{specs.join("  •  ")}</Text>}<View style={styles.footer}><Text style={styles.category}>{property.category}</Text><Text style={styles.details}>View Details ›</Text></View></View>
  </Pressable>;
}
const styles=StyleSheet.create({card:{marginBottom:18,overflow:"hidden",borderRadius:RADIUS.xl,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border,...SHADOW},pressed:{opacity:.86,transform:[{scale:.99}]},image:{width:"100%",height:220},placeholder:{alignItems:"center",justifyContent:"center",backgroundColor:COLORS.surfaceLight},placeholderText:{color:COLORS.assets,fontWeight:"900",letterSpacing:2},badges:{position:"absolute",left:12,right:12,top:12,flexDirection:"row",justifyContent:"space-between"},type:{overflow:"hidden",borderRadius:RADIUS.round,backgroundColor:"rgba(7,26,45,.86)",paddingHorizontal:12,paddingVertical:7,color:"white",fontSize:11,fontWeight:"900"},featured:{overflow:"hidden",borderRadius:RADIUS.round,backgroundColor:COLORS.assets,paddingHorizontal:12,paddingVertical:7,color:"white",fontSize:11,fontWeight:"900"},body:{padding:SPACING.lg},row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},price:{flex:1,fontSize:22,fontWeight:"900",color:COLORS.assets},status:{color:COLORS.success,fontWeight:"900"},sold:{color:COLORS.danger},title:{marginTop:10,fontSize:20,lineHeight:26,fontWeight:"900",color:COLORS.text},location:{marginTop:7,color:COLORS.textMuted,lineHeight:20},specs:{marginTop:10,color:COLORS.textSoft,fontWeight:"800",lineHeight:20},footer:{marginTop:15,paddingTop:13,borderTopWidth:1,borderTopColor:COLORS.border,flexDirection:"row",justifyContent:"space-between"},category:{color:COLORS.textMuted,fontWeight:"800"},details:{color:COLORS.assets,fontWeight:"900"}});
