export type PropertyStatus = "Available" | "Reserved" | "Sold";

export type Property = {
  id: string;
  title: string;
  type: string;
  category: string;
  location: string;
  locality: string;
  city: string;
  state: string;
  price: string;
  priceValue: number;
  negotiable: boolean;
  areaValue: number;
  areaUnit: string;
  dimensions: string;
  frontage: string;
  facing: string;
  roadWidth: string;
  bedrooms: number;
  bathrooms: number;
  parking: string;
  status: PropertyStatus;
  description: string;
  amenities: string[];
  imageUrls: string[];
  coverImageUrl: string;
  mapUrl: string;
  latitude: number | null;
  longitude: number | null;
  officeLocation: string;
  featured: boolean;
  updatedAt: string;
};
