import { useCallback, useMemo, useState } from "react";
import { Image, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import AppHeader from "../../components/AppHeader";
import { COLORS, RADIUS, SPACING } from "../../constants/theme";
import { getProperties } from "../../services/propertiesService";
import type { Property } from "../../types/property";

export default function PropertyListScreen() {
  const [items, setItems] = useState<Property[]>([]); const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setLoading(true); setError(""); setItems(await getProperties()); } catch (e) { setError(e instanceof Error ? e.message : "Properties load failed"); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return !q ? items : items.filter((p) => [p.title,p.location,p.type,p.category,p.status].join(" ").toLowerCase().includes(q)); }, [items, query]);
  return <SafeAreaView style={styles.safe}><AppHeader segment="JMK Assets"/><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}>
    <Text style={styles.title}>Properties</Text><Text style={styles.subtitle}>CRM se realtime synced JMK Assets listings</Text>
    <TextInput value={query} onChangeText={setQuery} placeholder="Search property, city, type..." placeholderTextColor={COLORS.textMuted} style={styles.search}/>
    {!!error && <View style={styles.error}><Text style={styles.errorText}>{error}</Text><Pressable onPress={load}><Text style={styles.retry}>Retry</Text></Pressable></View>}
    {!loading && !error && filtered.length===0 && <View style={styles.empty}><Text style={styles.emptyTitle}>No properties found</Text><Text style={styles.subtitle}>CRM me published property add karein.</Text></View>}
    {filtered.map((p)=><View key={p.id} style={styles.card}>{p.coverImageUrl?<Image source={{uri:p.coverImageUrl}} style={styles.image}/>:<View style={[styles.image,styles.placeholder]}><Text>No Photo</Text></View>}<View style={styles.body}><View style={styles.row}><Text style={styles.type}>{p.type}</Text><Text style={[styles.status,p.status==="Sold"&&styles.sold]}>{p.status}</Text></View><Text style={styles.cardTitle}>{p.title}</Text><Text style={styles.location}>{p.location}</Text><Text style={styles.price}>{p.price}{p.negotiable?" • Negotiable":""}</Text><Text style={styles.meta}>{p.areaValue} {p.areaUnit}{p.facing?` • ${p.facing} Facing`:""}{p.roadWidth?` • Road ${p.roadWidth}`:""}</Text><Text numberOfLines={3} style={styles.description}>{p.description}</Text><View style={styles.actions}>{p.mapUrl?<Pressable style={styles.secondary} onPress={()=>Linking.openURL(p.mapUrl)}><Text style={styles.secondaryText}>Map</Text></Pressable>:null}<Pressable style={styles.primary} onPress={()=>Linking.openURL(`https://wa.me/919826038401?text=${encodeURIComponent(`I am interested in ${p.title} at ${p.location}`)}`)}><Text style={styles.primaryText}>WhatsApp</Text></Pressable></View></View></View>)}
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},content:{padding:SPACING.lg,paddingBottom:40},title:{fontSize:28,fontWeight:"900",color:COLORS.text},subtitle:{marginTop:4,color:COLORS.textMuted},search:{marginTop:16,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.md,backgroundColor:COLORS.surface,padding:14,color:COLORS.text},error:{marginTop:16,padding:16,borderRadius:RADIUS.md,backgroundColor:"#FEE2E2"},errorText:{color:COLORS.danger,fontWeight:"700"},retry:{marginTop:8,color:COLORS.info,fontWeight:"900"},empty:{marginTop:24,padding:30,alignItems:"center",backgroundColor:COLORS.surface,borderRadius:RADIUS.lg},emptyTitle:{fontSize:18,fontWeight:"900",color:COLORS.text},card:{marginTop:18,overflow:"hidden",borderRadius:RADIUS.lg,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border},image:{width:"100%",height:210},placeholder:{alignItems:"center",justifyContent:"center",backgroundColor:COLORS.surfaceLight},body:{padding:16},row:{flexDirection:"row",justifyContent:"space-between"},type:{fontWeight:"900",color:COLORS.assets},status:{fontWeight:"900",color:COLORS.success},sold:{color:COLORS.danger},cardTitle:{marginTop:10,fontSize:21,fontWeight:"900",color:COLORS.text},location:{marginTop:6,color:COLORS.textMuted},price:{marginTop:12,fontSize:20,fontWeight:"900",color:COLORS.success},meta:{marginTop:8,color:COLORS.textSoft,fontWeight:"700"},description:{marginTop:10,color:COLORS.textMuted,lineHeight:20},actions:{marginTop:16,flexDirection:"row",gap:10},primary:{flex:1,padding:13,borderRadius:RADIUS.md,backgroundColor:COLORS.success,alignItems:"center"},primaryText:{color:"white",fontWeight:"900"},secondary:{flex:1,padding:13,borderRadius:RADIUS.md,borderWidth:1,borderColor:COLORS.assets,alignItems:"center"},secondaryText:{color:COLORS.assets,fontWeight:"900"}});
