import { useCallback, useMemo, useState } from "react";
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import AppHeader from "../../components/AppHeader";
import PropertyCard from "../../components/properties/PropertyCard";
import { COLORS, RADIUS, SPACING } from "../../constants/theme";
import { getProperties } from "../../services/propertiesService";
import type { Property } from "../../types/property";

const TYPES = ["All", "Residential", "Commercial", "Plot", "Agricultural"];
export default function PropertyListScreen() {
  const [items,setItems]=useState<Property[]>([]); const [query,setQuery]=useState(""); const [type,setType]=useState("All"); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{try{setLoading(true);setError("");setItems(await getProperties());}catch(e){setError(e instanceof Error?e.message:"Properties load failed");}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{void load();},[load]));
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter((p)=>(type==="All"||p.type===type)&&(!q||[p.title,p.location,p.locality,p.city,p.type,p.category,p.status,p.facing].join(" ").toLowerCase().includes(q)));},[items,query,type]);
  return <SafeAreaView style={styles.safe} edges={["top"]}><AppHeader segment="JMK Assets • Properties"/><FlatList data={filtered} keyExtractor={(item)=>item.id} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={COLORS.assets}/>} ListHeaderComponent={<><Text style={styles.title}>Properties</Text><Text style={styles.subtitle}>CRM और website से synced live property inventory</Text><View style={styles.summary}><View><Text style={styles.summaryValue}>{items.length}</Text><Text style={styles.summaryLabel}>Published</Text></View><View><Text style={styles.summaryValue}>{items.filter((p)=>p.status==="Available").length}</Text><Text style={styles.summaryLabel}>Available</Text></View><View><Text style={styles.summaryValue}>{items.filter((p)=>p.featured).length}</Text><Text style={styles.summaryLabel}>Featured</Text></View></View><TextInput value={query} onChangeText={setQuery} placeholder="Search title, city, locality, type..." placeholderTextColor={COLORS.textMuted} style={styles.search}/><FlatList horizontal data={TYPES} keyExtractor={(item)=>item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips} renderItem={({item})=><Pressable onPress={()=>setType(item)} style={[styles.chip,type===item&&styles.chipActive]}><Text style={[styles.chipText,type===item&&styles.chipTextActive]}>{item}</Text></Pressable>}/>{!!error&&<View style={styles.error}><Text style={styles.errorText}>{error}</Text><Pressable onPress={load}><Text style={styles.retry}>Retry</Text></Pressable></View>}<Text style={styles.result}>{filtered.length} properties found</Text></>} renderItem={({item})=><PropertyCard property={item} onPress={()=>router.push({pathname:"/property-details",params:{id:item.id}})}/>} ListEmptyComponent={!loading&&!error?<View style={styles.empty}><Text style={styles.emptyIcon}>⌂</Text><Text style={styles.emptyTitle}>No matching property</Text><Text style={styles.subtitle}>Search या filter बदलकर देखें.</Text></View>:null}/></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},content:{padding:SPACING.lg,paddingBottom:48},title:{fontSize:30,fontWeight:"900",color:COLORS.text},subtitle:{marginTop:5,color:COLORS.textMuted,lineHeight:20},summary:{marginTop:18,flexDirection:"row",justifyContent:"space-around",padding:16,borderRadius:RADIUS.lg,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border},summaryValue:{textAlign:"center",fontSize:22,fontWeight:"900",color:COLORS.assets},summaryLabel:{marginTop:3,color:COLORS.textMuted,fontSize:12,fontWeight:"800"},search:{marginTop:16,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.md,backgroundColor:COLORS.surface,padding:14,color:COLORS.text},chips:{gap:8,paddingVertical:14},chip:{paddingHorizontal:15,paddingVertical:9,borderRadius:RADIUS.round,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface},chipActive:{borderColor:COLORS.assets,backgroundColor:COLORS.assets},chipText:{color:COLORS.textSoft,fontWeight:"800"},chipTextActive:{color:"white"},result:{marginBottom:12,color:COLORS.textMuted,fontWeight:"800"},error:{marginBottom:16,padding:16,borderRadius:RADIUS.md,backgroundColor:"#FEE2E2"},errorText:{color:COLORS.danger,fontWeight:"700"},retry:{marginTop:8,color:COLORS.info,fontWeight:"900"},empty:{marginTop:24,padding:30,alignItems:"center",backgroundColor:COLORS.surface,borderRadius:RADIUS.lg},emptyIcon:{fontSize:48,color:COLORS.assets},emptyTitle:{marginTop:8,fontSize:18,fontWeight:"900",color:COLORS.text}});
