import { useCallback, useState } from "react";
import { Linking, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useLocalSearchParams } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import AppHeader from "../../components/AppHeader";
import PropertyGallery from "../../components/properties/PropertyGallery";
import { COLORS, RADIUS, SHADOW, SPACING } from "../../constants/theme";
import { getPropertyById } from "../../services/propertiesService";
import type { Property } from "../../types/property";

const PHONE="9826038401";
export default function PropertyDetailsScreen(){const {id}=useLocalSearchParams<{id:string}>();const [property,setProperty]=useState<Property|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const load=useCallback(async()=>{if(!id)return;try{setLoading(true);setError("");setProperty(await getPropertyById(String(id)));}catch(e){setError(e instanceof Error?e.message:"Property load failed");}finally{setLoading(false);}},[id]);useFocusEffect(useCallback(()=>{void load();},[load]));
if(loading)return <SafeAreaView style={styles.safe}><AppHeader segment="JMK Assets • Property Details"/><View style={styles.center}><Text style={styles.loading}>Property loading...</Text></View></SafeAreaView>;
if(error||!property)return <SafeAreaView style={styles.safe}><AppHeader segment="JMK Assets • Property Details"/><View style={styles.center}><Text style={styles.error}>{error||"Property not found"}</Text><Pressable style={styles.retryButton} onPress={load}><Text style={styles.retryText}>Retry</Text></Pressable></View></SafeAreaView>;
const images=[...new Set([property.coverImageUrl,...property.imageUrls].filter(Boolean))];const message=`Hello JMK Group, I am interested in ${property.title} at ${property.location}. Please share complete details and arrange a site visit.`;const map=property.mapUrl||(property.latitude&&property.longitude?`https://www.google.com/maps/search/?api=1&query=${property.latitude},${property.longitude}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(property.location)}`);const specs=[["Area",property.areaValue?`${property.areaValue} ${property.areaUnit}`:"On Request"],["Bedrooms",property.bedrooms||"N/A"],["Bathrooms",property.bathrooms||"N/A"],["Parking",property.parking||"On Request"],["Facing",property.facing||"Not specified"],["Road Width",property.roadWidth||"Not specified"],["Dimensions",property.dimensions||"On Request"],["Frontage",property.frontage||"On Request"]];
return <SafeAreaView style={styles.safe} edges={["top"]}><AppHeader segment="JMK Assets • Property Details"/><ScrollView contentContainerStyle={styles.content}><PropertyGallery images={images} title={property.title}/><View style={styles.headingRow}><View style={styles.tag}><Text style={styles.tagText}>{property.type}</Text></View><Text style={[styles.status,property.status==="Sold"&&styles.sold]}>{property.status}</Text></View><Text style={styles.title}>{property.title}</Text><Text style={styles.location}>⌖ {property.location}</Text><Text style={styles.price}>{property.price}</Text>{property.negotiable&&<Text style={styles.negotiable}>Negotiable</Text>}<View style={styles.actionRow}><Pressable style={styles.share} onPress={()=>Share.share({message:`${property.title}\n${property.price}\n${property.location}`})}><Text style={styles.shareText}>Share</Text></Pressable><Pressable style={styles.map} onPress={()=>Linking.openURL(map)}><Text style={styles.mapText}>Open Map</Text></Pressable></View><View style={styles.panel}><Text style={styles.sectionTitle}>Property Details</Text><View style={styles.grid}>{specs.map(([label,value])=><View key={String(label)} style={styles.spec}><Text style={styles.specLabel}>{label}</Text><Text style={styles.specValue}>{value}</Text></View>)}</View></View><View style={styles.panel}><Text style={styles.sectionTitle}>Description</Text><Text style={styles.description}>{property.description||"Complete property information is available from JMK Assets."}</Text></View><View style={styles.panel}><Text style={styles.sectionTitle}>Amenities</Text>{(property.amenities.length?property.amenities:["Site visit support","Price guidance","Documentation assistance"]).map((item)=><Text key={item} style={styles.amenity}>✓  {item}</Text>)}</View><View style={styles.actions}><Pressable style={styles.call} onPress={()=>Linking.openURL(`tel:${PHONE}`)}><Text style={styles.actionText}>Call Now</Text></Pressable><Pressable style={styles.whatsapp} onPress={()=>Linking.openURL(`https://wa.me/91${PHONE}?text=${encodeURIComponent(message)}`)}><Text style={styles.actionText}>WhatsApp</Text></Pressable></View></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},content:{padding:SPACING.lg,paddingBottom:48},center:{flex:1,alignItems:"center",justifyContent:"center",padding:24},loading:{color:COLORS.textMuted,fontWeight:"800"},error:{color:COLORS.danger,fontWeight:"800",textAlign:"center"},retryButton:{marginTop:15,paddingHorizontal:24,paddingVertical:12,borderRadius:RADIUS.round,backgroundColor:COLORS.assets},retryText:{color:"white",fontWeight:"900"},headingRow:{marginTop:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},tag:{borderRadius:RADIUS.round,backgroundColor:COLORS.assets,paddingHorizontal:13,paddingVertical:7},tagText:{color:"white",fontWeight:"900"},status:{color:COLORS.success,fontWeight:"900"},sold:{color:COLORS.danger},title:{marginTop:14,fontSize:28,lineHeight:34,fontWeight:"900",color:COLORS.text},location:{marginTop:8,color:COLORS.textMuted,lineHeight:21},price:{marginTop:14,fontSize:27,fontWeight:"900",color:COLORS.assets},negotiable:{marginTop:4,color:COLORS.success,fontWeight:"800"},actionRow:{marginTop:16,flexDirection:"row",gap:10},share:{flex:1,alignItems:"center",padding:13,borderRadius:RADIUS.md,borderWidth:1,borderColor:COLORS.assets},shareText:{color:COLORS.assets,fontWeight:"900"},map:{flex:1,alignItems:"center",padding:13,borderRadius:RADIUS.md,backgroundColor:COLORS.navy},mapText:{color:"white",fontWeight:"900"},panel:{marginTop:18,padding:18,borderRadius:RADIUS.xl,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border,...SHADOW},sectionTitle:{fontSize:20,fontWeight:"900",color:COLORS.text},grid:{marginTop:12,flexDirection:"row",flexWrap:"wrap",gap:10},spec:{width:"47%",padding:13,borderRadius:RADIUS.md,backgroundColor:COLORS.surfaceLight},specLabel:{fontSize:11,color:COLORS.textMuted,fontWeight:"900",textTransform:"uppercase"},specValue:{marginTop:5,color:COLORS.text,fontWeight:"900"},description:{marginTop:10,color:COLORS.textSoft,lineHeight:23},amenity:{marginTop:10,color:COLORS.textSoft,fontWeight:"700"},actions:{marginTop:20,flexDirection:"row",gap:10},call:{flex:1,alignItems:"center",padding:16,borderRadius:RADIUS.round,backgroundColor:COLORS.info},whatsapp:{flex:1,alignItems:"center",padding:16,borderRadius:RADIUS.round,backgroundColor:COLORS.success},actionText:{color:"white",fontWeight:"900"}});
